#:schema node_modules/wrangler/config-schema.json
name = "proxy"
main = "src/index.ts"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "typeauth_keys", id = "9744321d80574d39a97f2b82416e9951", preview_id = "9744321d80574d39a97f2b82416e9951" },
    { binding = "refill_timestamp", id = "33cec523d07b4711b2f3be0f286ddef6", preview_id = "33cec523d07b4711b2f3be0f286ddef6" },
    { binding = "proxy_conf", id = "de34de446bae4219b0a4a734516025a5", preview_id = "de34de446bae4219b0a4a734516025a5" },
]

services = [
    { binding = "RATELIMIT", service = "storage-state" },
    { binding = "REMAIN", service = "storage-state" },
    { binding = "LLMCACHE", service = "ai-cache" },
    { binding = "ABUSE", service = "abuse" },


]

analytics_engine_datasets = [{ binding = "ANALYTICS", dataset = "analytics" }]


# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# Bind a Vectorize index. Use to store and query vector embeddings for semantic search, classification and other vector search use-cases.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#vectorize-indexes
# [[vectorize]]
# binding = "MY_INDEX"
# index_name = "my-index"
